#Application properties
server:
  port: 8081
spring:
  application:
    name: customer-api

  #DB connection properties
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ccp-ms
    username: root
    password: root

  #JPA properties
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

#Server registry properties
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: localhost

#Actuator properties
management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
